name: mybb
services:
  mybb:
    container_name: mybb
    hostname: mybb
    image: gugajedi/mybb-nginx:php83
    ports:
      - "8081:80"
    networks:
      - mybb-network
    volumes:
      - ./app:/var/www/html:rw
    healthcheck:
      test: ["CMD", "php-fpm", "-t"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped

networks:
  mybb-network:
    driver: bridge
    name: mybb-network
